<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
         $this->load->model('siswa_model');
    }

    public function index()
    {	$jenis = $this->input->post('jenis');
    $username = $this->input->post('username');

		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('home');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('login');
		}
		else
		{	
			

			if($jenis==1){
				$guru = $this->siswa_model->select_nama_guru($username);
				
			

					if(strtolower($this->input->post('username')) == $guru->nik  &&
					$this->input->post('password') == $guru->pass_guru)
					
					{
					$this->session->set_userdata('logined', $this->input->post('username'));
				
					redirect("home/index");
					}
						else 
						{
						redirect("/");


						}
						
			}
			elseif($jenis==2){
				$ortu = $this->siswa_model->select_nama_ortu($username);
				
			

					if(strtolower($this->input->post('username')) == $ortu->id_ortu  &&
					$this->input->post('password') == $ortu->pass)
					
					{
					$this->session->set_userdata('logined', $this->input->post('username'));
				
					redirect("home/index3");
					}
						else 
						{
						redirect("/");
				

						}
						
			}
			elseif($jenis==3){
				$siswa = $this->siswa_model->select_nama_siswa($username);
				
			

					if(strtolower($this->input->post('username')) == $siswa->nis  &&
					$this->input->post('password') == $siswa->pass_siswa)
					
					{
					$this->session->set_userdata('logined', $this->input->post('username'));
				
					redirect("home/index2");
					}
						else 
						{
						redirect("/");


						}
						
			}
			else{
redirect("/");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */